version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cafe-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cafe_db
      MYSQL_USER: cafe_user
      MYSQL_PASSWORD: your_password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  mysql-data: